### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/InfiniteInfernal#1]
- [x] **Working**
- [x] 自然黑化生成概率改为每个玩家附近最多生成的黑化数量限制
- [x] 控制每个玩家附近生成的怪物总量和世界范围的怪物总量
- [x] 特定区域的刷怪设置
- [x] 按怪物等级控制怪物仇恨距离，特定药水效果可以减少/增加附近怪物对其的仇恨值/仇恨距离
---
- [x] **Working**
- [x] 特定属性可以增加部分物品的掉落权重
- [x] 特定属性可以减少整体掉率
- [x] 友伤惩罚
- [ ] 玩家的某种属性可以提升稀有物品的掉落几率（具体待议，例如 setdrop 的额外参数
---
- [x] **Working**
- [x] 技能实例 （见下
- [x] 怪物总是不会 target 到创造/旁观玩家
---
- [x] **Working**
- [x] `mobs.yml` 分离为为 `mobs/mob-name.yml`
- [x] 自定义 mob 可在特定群系和等级范围内生成
- [x] 自定义 mob 可有标准掉落列表之外的特殊掉落，出率与等级相关
---
- [ ] **Working**
- [ ] 清理、简化、格式化 console 输出
- [ ] 玩家相关的数据（仇恨值、幸运/霉运影响的掉落等）写入计分板
- [ ] API（低优先

**Comment by phoenixlzx** [comment]
#### 配置文件

- [x] `config.yml`

```
lang: en
nametag: '[INFERNAL] {level.prefix} {mob.name} Level {level.level}'
tags:
- 'im_mob'
- 'im_mob_{mob}'
- 'im_level_{level}'
bossbar:
  enable: true
  killsuffix: '[KILLED]'
addeffects:
  target_lost: effect:BLINDNESS:10
  disorder: effect:CONFUSION:10
  dementia: effect:SLOW_DIGGING:10
worlds:
  world1:
    disable-natural-spawning: true
    max-mob-per-player: 10
    max-mob-in-world: 240
    spawn-range-min: 48
    spawn-range-max: 120
    mob-tick-interval: 60
    aggro:
      range:
        min: 20
        max: 128
      base: 10
      dec: effect:INVISIBILITY:2
      inc: attribute:UNLUCK:2
    looting:
      global: 70
      overall:
        inc: enchant:LOOTING:5
        dec: attribute:UNLUCK:5
      dynamic:
        inc: attribute:LUCK:10
        dec: attribute:UNLUCK:5
    friendlyfire:
      enable: true
      effect: effect:UNLUCK:4:600 # give unluck level 5 for 600 ticks per friendly hit
    broadcast:
      default: NEAR
      range: 160
```

- [ ] `levels/level-1.yml`

```
level: 1
prefix: "[SIRENS]"
attr:
  health: 50
  damage: 2
  damageResist: 0
  exp: 5
  aggro: 48
spawn:
  from: 100
  to: 2000
  weight: 1
```

- [ ] `abilities/set-1.yml`

```
abilities:
  potionhit:
    effect: POISON
    amplifier: 1
    duration: 60
    weight: 50
  projectile:
    type: ARROW
    speed: 3
    burst: 3
    burstInterval: 2
    cone: true
    range: 3
    weight: 100
```

- [ ] `mobs/mob-1.yml`

```
name: 'A custom mob'
id: 'mob-1'
type: ZOMBIE
abilities:
- set-1
nbttags: '{nbt-json-data}' # leave blank to use level definitions
spawn:
  autoSpawn: true
  weight: 100
  levels:
  - 1-3
  worlds:
  - world1
  - world2
  biomes:
  - PLAINS
  - DESERT
  - ANY
loot:
  vanilla: false
  imloot: true
  special:
    chance: 20
    list:
    - loot_item_1:100
    - loot_item_2:100
```

- [x] `regions/region-1.yml`

```
region:
  world: world1
  maxX: 200
  maxY: 55
  maxZ: 400
  minX: 100
  minY: 30
  minZ: 200
mobs:
- mob-1:100  # overrides spawn settings in mob config
```

- [x] `loot.yml`

```
items:
  i1:
    nbt: 'nbt base64 string'
    dynamic: true
map:
  level-1:
    i1: 100
```

- [ ] `messages.yml`

```
playerkill:
- '{player.name} killed {mob.name} with {player.item}'
mobkill:
- '{player.name} killed by {mob.name}'
drop:
- '{player.name} looted {drop.item}'
specialdrop:
- '{drop.special} now belongs to {player.name}'
nodrop:
- '{player.name} found nothing'
```

#### Commands

`im` / `ii` should be both available as command prefix

| command | permission | desc |
| --- | --- | --- |
| `/im reload` | `im.reload` | Reload configuration |
| `/im spawn <mob> [world] [x] [y] [z]` | `im.spawn` | Spawn mob at target/specific location |
| `/im addloot [item] <dynamic>` | `im.addloot` | Add item in hand to loot table |
| `/im getloot [item]` | `im.getloot` | Get specific or random loot item |
| `/im setdrop [item] [level] [weight]` | `im.setdrop` | Set specified item to drop map |
| `/im inspect [level\|item] [level-id\|item-id]` | `im.inspect` | Check specified level or item looting information |
| `/imi <me\|near\|all\|off>` | `imi.command` | Toggle broadcast filter option |

WIP
